name: LootRoll
version: '1.0'
main: me.newtale.lootRoll.LootRoll
api-version: '1.21'
authors: [ Ney ]
website: https://newtale.me/
depend: [ProtocolLib, MythicMobs]
softdepend: [MMOItems, Parties, MMOCore]

commands:
  lootroll:
    description: Main LootRoll command
    usage: /lootroll [reload]
    permission: lootroll.admin
  roll:
    description: Roll for loot
    usage: /roll [item_name]
    aliases: [r]
  rollf:
    description: Fallback roll for loot items (lower priority)
    usage: /rollf [item_name]
    aliases: [ rf ]
  rollcancel:
    description: Cancel a roll
    usage: /rollcancel [item_name]
    aliases: [ rc ]
permissions:
  lootroll.admin:
    description: Allows use of admin commands
    default: op