name: LootRoll
version: "${version}"
main: me.newtale.lootroll.LootRoll
api-version: "1.21"
authors: [Ney]
website: https://ney-dev.xyz/
depend: [packetevents]
softdepend: [MMOItems, MythicMobs, Parties, MMOCore, Nexo]

commands:
  lootroll:
    description: Main LootRoll command
    usage: /lootroll [reload]
    permission: lootroll.admin
  roll:
    description: Roll for loot
    usage: /roll [item_name]
    aliases: [r, need]
  greed:
    description: Greed roll for loot items (lower priority)
    usage: /greed [item_name]
  pass:
    description: Pass the item (cancel your roll)
    usage: /pass [item_name]
permissions:
  lootroll.admin:
    description: Allows use of admin commands
    default: op
